### PR TITLE
maven -> gradle wrapper

### PR DESCRIPTION
**Pull request by NagyGa1**
Hi,
I am planning to send a few pull requests for your consideration, this is the first one, moving from maven to gradle with wrapper, so it can be run on any computer with just java preinstalled, using ./gradlew or gradlew.bat

Subsequent pull requests will be:
* update to latest kotlin and coroutines
* OpenJDK compatibility
* Java 13 compatibility

### CODE REVIEW

**Comment by wumo** [comment]
Thank you for your contribution.
I have merged your latest PR, so this one will be closed.

As for the JDK 13 compatibility, JavaFX has been seperated from JDK since 11. So you will need to add JavaFX as additional dependency as shown in [Getting Started with JavaFX 13](https://openjfx.io/openjfx-docs/#gradle). Another pain point is that `org.openjfx.javafxplugin` is not compatible with JDK 8, thus we may have to conditionally add javafx dependency based on the version of underlying JDK.

**Comment by NagyGa1** [comment]
Thank you. Sorry for the mixup, haven't done git this fashion for a while.

Did JDK 13 already: https://github.com/NagyGa1/Reinforcement-Learning-An-Introduction/commit/38dd331e23938a929ec491aefa8c5de76ccefdfc

Initially 13 didn't work due to some bytecode incompatibility, so I did it on 12, but now it seems to work, not sure why.

Also moved logback -> log4j2 and removed the level settings from code: https://github.com/NagyGa1/Reinforcement-Learning-An-Introduction/commit/53b1fe40e27cd48c27fabe460d6f09f566311c73

Do you want to see these as pull requests?

**Comment by wumo** [comment]
@NagyGa1 Yes, make a pull request.

I have tested your implementation, it works fine in my computer.
There is one problem with your `build.gradle` script. If the user has only JDK 8 installed, then the compilation will fail with exception:
```java
java.lang.UnsupportedClassVersionError: org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> org/openjfx/gradle/JavaFXPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
So we need one way to conditionally add javafx dependency based on the version of underlying JDK.

**Comment by NagyGa1** [comment]
Maybe could keep it in a jdk8 branch that gets rebased onto master any time it is needed?

**Pull request closed without merging**
